name: Ping Zentari Health Endpoints

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes UTC
  workflow_dispatch:       # Allows manual trigger too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping dev endpoint
        run: curl -sSf https://zentari-dev.onrender.com/health

      - name: Ping prod endpoint
        run: curl -sSf https://zentari-prod.onrender.com/health
